@host = http://localhost:3000

### Cadastro de usuário

POST {{host}}/cadastro
Content-Type: application/json

{
  "username": "gabu",
  "email": "gabu@gmail.com",
  "senha": "897654321"
}

### Array de usuários
GET {{host}}/usuarios

### Deletar usuário

DELETE {{host}}/usuarios/7

### Array de livros

GET {{host}}/livros

### Cadastrar livro

POST {{host}}/cadastro/livro
Content-Type: application/json

{
  "titulo": "teste",
  "autor": "testeovaldo da silva",
  "editora": "testando",
  "ano_pub": 1984
}

### Deletar livro 

DELETE {{host}}/livros/

### Login válido

POST {{host}}/login
Content-Type: application/json

{
  "email": "heleny@example.com",
  "senha": "adorodesenhar"
}

### Login inválido

POST {{host}}/login
Content-Type: application/json

{
  "email": "heleny@gmail.com",
  "senha": "adorodesenhar"
}