@host = http://localhost:3000

### Cadastro de usuário

POST {{host}}/cadastro

Content-Type: application/json

{
  "username": "teste",
  "email": "teste@exemplo.com",
  "password": "12345678"
}

### Array de usuários
GET {{host}}/users

### DELETE USER

DELETE {{host}}/users/9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d
